services:
  bot:
    image: leroideskiwis/omega-bot:v1.0.1
    volumes:
      - ./database.sqlite:/opt/omega-bot/database.sqlite
    restart: always
    build:
        context: .
        dockerfile: Dockerfile