services:
  bot:
    image: leroideskiwis/omega-bot:latest
    volumes:
      - ./data/:/opt/omega-bot/data
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_CHANNEL=${LOG_CHANNEL}