name: docker

on:
  push:
    tags: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leroideskiwis
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract Git tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            leroideskiwis/omega-bot:latest
            leroideskiwis/omega-bot:${{ env.TAG }}
